version: 2.1

orbs:
  codacy: codacy/base@10.3.0

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: compile_and_test
          steps_before_sbt:
            - run:
                name: Override OpenJdk (java8 -> java11)
                command: sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          steps:
            - run:
                name: Check Scalafmt Sbt
                command: sbt scalafmtSbtCheck
            - run:
                name: Check Scalafmt Sources
                command: sbt scalafmtCheckAll
            - run:
                name: Compile
                command: sbt +Test/compile
            - run:
                name: Install Clang for Scala Native
                command: sudo apt-get update && sudo apt-get install clang
            - run:
                name: Test
                command: sbt +test
          use_sbt_native_client: true
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_sonatype
          context: CodacyAWS
          steps_before_sbt:
            - run:
                name: Override OpenJdk (java8 -> java11)
                command: sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          steps:
            - run:
                name: Publish to Sonatype
                command: sbt retrieveGPGKeys +publishSigned sonatypeBundleRelease
          requires:
            - compile_and_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_sonatype
